[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = 1

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
max-line-length = 88
exclude = "local,node_modules"
extend-ignore = "E203,"
max-complexity = 10
